
[api_server]
conn_type ="grpc"
ip = "192.168.0.102"
port =  11000
max_pool_size =  20
api_refer_type = "proto"
api_table_filepath= "'./proto/','./'"
api_outpath = "api/"


[cache_db]
connector = "redis"
worker_node = 12
host = "192.168.0.110"
port = 6379
username = ""
password =""
filepath= ""
