// Code generated by protoc-gen-go. DO NOT EDIT.
// source: StoreMod.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Move-Phase-SnapMod
type MovePhaseSnapMod struct {
	//  flaging
	Turns                int32        `protobuf:"varint,1,opt,name=turns,proto3" json:"turns,omitempty"`
	IsHostReady          bool         `protobuf:"varint,2,opt,name=is_host_ready,json=isHostReady,proto3" json:"is_host_ready,omitempty"`
	IsDuelReady          bool         `protobuf:"varint,3,opt,name=is_duel_ready,json=isDuelReady,proto3" json:"is_duel_ready,omitempty"`
	HostVal              int32        `protobuf:"varint,4,opt,name=host_val,json=hostVal,proto3" json:"host_val,omitempty"`
	DuelVal              int32        `protobuf:"varint,5,opt,name=duel_val,json=duelVal,proto3" json:"duel_val,omitempty"`
	HostOpt              MovePhaseOpt `protobuf:"varint,6,opt,name=host_opt,json=hostOpt,proto3,enum=ULZProto.MovePhaseOpt" json:"host_opt,omitempty"`
	DuelOpt              MovePhaseOpt `protobuf:"varint,7,opt,name=duel_opt,json=duelOpt,proto3,enum=ULZProto.MovePhaseOpt" json:"duel_opt,omitempty"`
	HostCard             []*EventCard `protobuf:"bytes,8,rep,name=host_card,json=hostCard,proto3" json:"host_card,omitempty"`
	DuelCard             []*EventCard `protobuf:"bytes,9,rep,name=duel_card,json=duelCard,proto3" json:"duel_card,omitempty"`
	HostTrigSkl          []*SkillSet  `protobuf:"bytes,10,rep,name=host_trig_skl,json=hostTrigSkl,proto3" json:"host_trig_skl,omitempty"`
	DuelTrigSkl          []*SkillSet  `protobuf:"bytes,11,rep,name=duel_trig_skl,json=duelTrigSkl,proto3" json:"duel_trig_skl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MovePhaseSnapMod) Reset()         { *m = MovePhaseSnapMod{} }
func (m *MovePhaseSnapMod) String() string { return proto.CompactTextString(m) }
func (*MovePhaseSnapMod) ProtoMessage()    {}
func (*MovePhaseSnapMod) Descriptor() ([]byte, []int) {
	return fileDescriptor_98fa4925a5e51b0e, []int{0}
}

func (m *MovePhaseSnapMod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovePhaseSnapMod.Unmarshal(m, b)
}
func (m *MovePhaseSnapMod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovePhaseSnapMod.Marshal(b, m, deterministic)
}
func (m *MovePhaseSnapMod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovePhaseSnapMod.Merge(m, src)
}
func (m *MovePhaseSnapMod) XXX_Size() int {
	return xxx_messageInfo_MovePhaseSnapMod.Size(m)
}
func (m *MovePhaseSnapMod) XXX_DiscardUnknown() {
	xxx_messageInfo_MovePhaseSnapMod.DiscardUnknown(m)
}

var xxx_messageInfo_MovePhaseSnapMod proto.InternalMessageInfo

func (m *MovePhaseSnapMod) GetTurns() int32 {
	if m != nil {
		return m.Turns
	}
	return 0
}

func (m *MovePhaseSnapMod) GetIsHostReady() bool {
	if m != nil {
		return m.IsHostReady
	}
	return false
}

func (m *MovePhaseSnapMod) GetIsDuelReady() bool {
	if m != nil {
		return m.IsDuelReady
	}
	return false
}

func (m *MovePhaseSnapMod) GetHostVal() int32 {
	if m != nil {
		return m.HostVal
	}
	return 0
}

func (m *MovePhaseSnapMod) GetDuelVal() int32 {
	if m != nil {
		return m.DuelVal
	}
	return 0
}

func (m *MovePhaseSnapMod) GetHostOpt() MovePhaseOpt {
	if m != nil {
		return m.HostOpt
	}
	return MovePhaseOpt_NO_MOVE
}

func (m *MovePhaseSnapMod) GetDuelOpt() MovePhaseOpt {
	if m != nil {
		return m.DuelOpt
	}
	return MovePhaseOpt_NO_MOVE
}

func (m *MovePhaseSnapMod) GetHostCard() []*EventCard {
	if m != nil {
		return m.HostCard
	}
	return nil
}

func (m *MovePhaseSnapMod) GetDuelCard() []*EventCard {
	if m != nil {
		return m.DuelCard
	}
	return nil
}

func (m *MovePhaseSnapMod) GetHostTrigSkl() []*SkillSet {
	if m != nil {
		return m.HostTrigSkl
	}
	return nil
}

func (m *MovePhaseSnapMod) GetDuelTrigSkl() []*SkillSet {
	if m != nil {
		return m.DuelTrigSkl
	}
	return nil
}

// AD-Phase-SnapMod
type ADPhaseSnapMod struct {
	Turns                int32          `protobuf:"varint,1,opt,name=turns,proto3" json:"turns,omitempty"`
	FirstAttack          PlayerSide     `protobuf:"varint,2,opt,name=first_attack,json=firstAttack,proto3,enum=ULZProto.PlayerSide" json:"first_attack,omitempty"`
	CurrPhase            PlayerSide     `protobuf:"varint,3,opt,name=curr_phase,json=currPhase,proto3,enum=ULZProto.PlayerSide" json:"curr_phase,omitempty"`
	EventPhase           EventHookPhase `protobuf:"varint,4,opt,name=event_phase,json=eventPhase,proto3,enum=ULZProto.EventHookPhase" json:"event_phase,omitempty"`
	HostVal              int32          `protobuf:"varint,5,opt,name=host_val,json=hostVal,proto3" json:"host_val,omitempty"`
	DuelVal              int32          `protobuf:"varint,6,opt,name=duel_val,json=duelVal,proto3" json:"duel_val,omitempty"`
	HostCard             []*EventCard   `protobuf:"bytes,7,rep,name=host_card,json=hostCard,proto3" json:"host_card,omitempty"`
	DuelCard             []*EventCard   `protobuf:"bytes,8,rep,name=duel_card,json=duelCard,proto3" json:"duel_card,omitempty"`
	HostTrigSkl          []*SkillSet    `protobuf:"bytes,9,rep,name=host_trig_skl,json=hostTrigSkl,proto3" json:"host_trig_skl,omitempty"`
	DuelTrigSkl          []*SkillSet    `protobuf:"bytes,10,rep,name=duel_trig_skl,json=duelTrigSkl,proto3" json:"duel_trig_skl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ADPhaseSnapMod) Reset()         { *m = ADPhaseSnapMod{} }
func (m *ADPhaseSnapMod) String() string { return proto.CompactTextString(m) }
func (*ADPhaseSnapMod) ProtoMessage()    {}
func (*ADPhaseSnapMod) Descriptor() ([]byte, []int) {
	return fileDescriptor_98fa4925a5e51b0e, []int{1}
}

func (m *ADPhaseSnapMod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ADPhaseSnapMod.Unmarshal(m, b)
}
func (m *ADPhaseSnapMod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ADPhaseSnapMod.Marshal(b, m, deterministic)
}
func (m *ADPhaseSnapMod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ADPhaseSnapMod.Merge(m, src)
}
func (m *ADPhaseSnapMod) XXX_Size() int {
	return xxx_messageInfo_ADPhaseSnapMod.Size(m)
}
func (m *ADPhaseSnapMod) XXX_DiscardUnknown() {
	xxx_messageInfo_ADPhaseSnapMod.DiscardUnknown(m)
}

var xxx_messageInfo_ADPhaseSnapMod proto.InternalMessageInfo

func (m *ADPhaseSnapMod) GetTurns() int32 {
	if m != nil {
		return m.Turns
	}
	return 0
}

func (m *ADPhaseSnapMod) GetFirstAttack() PlayerSide {
	if m != nil {
		return m.FirstAttack
	}
	return PlayerSide_HOST
}

func (m *ADPhaseSnapMod) GetCurrPhase() PlayerSide {
	if m != nil {
		return m.CurrPhase
	}
	return PlayerSide_HOST
}

func (m *ADPhaseSnapMod) GetEventPhase() EventHookPhase {
	if m != nil {
		return m.EventPhase
	}
	return EventHookPhase_gameset_start
}

func (m *ADPhaseSnapMod) GetHostVal() int32 {
	if m != nil {
		return m.HostVal
	}
	return 0
}

func (m *ADPhaseSnapMod) GetDuelVal() int32 {
	if m != nil {
		return m.DuelVal
	}
	return 0
}

func (m *ADPhaseSnapMod) GetHostCard() []*EventCard {
	if m != nil {
		return m.HostCard
	}
	return nil
}

func (m *ADPhaseSnapMod) GetDuelCard() []*EventCard {
	if m != nil {
		return m.DuelCard
	}
	return nil
}

func (m *ADPhaseSnapMod) GetHostTrigSkl() []*SkillSet {
	if m != nil {
		return m.HostTrigSkl
	}
	return nil
}

func (m *ADPhaseSnapMod) GetDuelTrigSkl() []*SkillSet {
	if m != nil {
		return m.DuelTrigSkl
	}
	return nil
}

func init() {
	proto.RegisterType((*MovePhaseSnapMod)(nil), "ULZProto.MovePhaseSnapMod")
	proto.RegisterType((*ADPhaseSnapMod)(nil), "ULZProto.ADPhaseSnapMod")
}

func init() { proto.RegisterFile("StoreMod.proto", fileDescriptor_98fa4925a5e51b0e) }

var fileDescriptor_98fa4925a5e51b0e = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x95, 0xa6, 0x4e, 0x9c, 0x31, 0x8d, 0xc0, 0x44, 0xc8, 0x94, 0x4b, 0x94, 0x53, 0x4e,
	0x16, 0xa4, 0x12, 0x88, 0x63, 0x20, 0x48, 0x3d, 0xd4, 0x6a, 0x64, 0x53, 0x0e, 0xb9, 0x58, 0x4b,
	0x76, 0x69, 0x2d, 0xaf, 0xb2, 0xd6, 0xee, 0x38, 0x52, 0x5f, 0x89, 0x37, 0xe2, 0xc6, 0xa3, 0xa0,
	0x19, 0xbb, 0x09, 0x45, 0x4a, 0x55, 0x7a, 0xf3, 0xce, 0xfc, 0xdf, 0xcc, 0xee, 0xfc, 0x63, 0x18,
	0x66, 0x68, 0xac, 0x4a, 0x8c, 0x8c, 0x2b, 0x6b, 0xd0, 0x84, 0xfe, 0xd5, 0xc5, 0x6a, 0x49, 0x5f,
	0xa7, 0xb0, 0x10, 0x28, 0x9a, 0xe8, 0xe9, 0xe8, 0xcb, 0x56, 0x6d, 0xf0, 0xdc, 0x98, 0x72, 0x79,
	0x23, 0x9c, 0x6a, 0xa2, 0x93, 0xdf, 0x5d, 0x78, 0x9e, 0x98, 0xad, 0xe2, 0x58, 0xb6, 0x11, 0x55,
	0x62, 0x64, 0x38, 0x02, 0x0f, 0x6b, 0xbb, 0x71, 0x51, 0x67, 0xdc, 0x99, 0x7a, 0x69, 0x73, 0x08,
	0x27, 0x70, 0x52, 0xb8, 0xfc, 0xc6, 0x38, 0xcc, 0xad, 0x12, 0xf2, 0x36, 0x3a, 0x1a, 0x77, 0xa6,
	0x7e, 0x1a, 0x14, 0xee, 0xdc, 0x38, 0x4c, 0x29, 0xd4, 0x6a, 0x64, 0xad, 0x74, 0xab, 0xe9, 0xde,
	0x69, 0x16, 0xb5, 0xd2, 0x8d, 0xe6, 0x35, 0xf8, 0x5c, 0x64, 0x2b, 0x74, 0x74, 0xcc, 0x0d, 0xfa,
	0x74, 0xfe, 0x26, 0x34, 0xa5, 0x98, 0xa5, 0x94, 0xd7, 0xa4, 0xe8, 0x4c, 0xa9, 0x77, 0x2d, 0x65,
	0x2a, 0x8c, 0x7a, 0xe3, 0xce, 0x74, 0x38, 0x7b, 0x15, 0xdf, 0xbd, 0x33, 0xde, 0xbd, 0xe0, 0xb2,
	0xc2, 0xa6, 0xda, 0x65, 0x85, 0x84, 0x70, 0x35, 0x42, 0xfa, 0x0f, 0x23, 0xa4, 0x23, 0xe4, 0x2d,
	0x0c, 0xb8, 0xcb, 0x5a, 0x58, 0x19, 0xf9, 0xe3, 0xee, 0x34, 0x98, 0xbd, 0xdc, 0x33, 0x3c, 0xc1,
	0xcf, 0xc2, 0xca, 0x94, 0xef, 0x42, 0x5f, 0x44, 0x70, 0x13, 0x26, 0x06, 0x0f, 0x10, 0xa4, 0x62,
	0xe2, 0x3d, 0x9c, 0x70, 0x0f, 0xb4, 0xc5, 0x75, 0xee, 0x4a, 0x1d, 0x01, 0x53, 0xe1, 0x9e, 0xca,
	0xca, 0x42, 0xeb, 0x4c, 0x61, 0x1a, 0x90, 0xf0, 0xab, 0x2d, 0xae, 0xb3, 0x52, 0x13, 0xc7, 0x9d,
	0x76, 0x5c, 0x70, 0x98, 0x23, 0x61, 0xcb, 0x4d, 0x7e, 0x75, 0x61, 0x38, 0x5f, 0x3c, 0xc2, 0xe0,
	0x0f, 0xf0, 0xec, 0x47, 0x61, 0x1d, 0xe6, 0x02, 0x51, 0xac, 0x4b, 0xf6, 0x77, 0x38, 0x1b, 0xed,
	0xeb, 0x2f, 0xb5, 0xb8, 0x55, 0x36, 0x2b, 0xa4, 0x4a, 0x03, 0x56, 0xce, 0x59, 0x18, 0x9e, 0x01,
	0xac, 0x6b, 0x6b, 0xf3, 0x8a, 0x7a, 0xb0, 0xe5, 0x87, 0xb0, 0x01, 0xe9, 0xf8, 0x2a, 0xe1, 0x47,
	0x08, 0x14, 0x4d, 0xa7, 0xa5, 0x8e, 0x99, 0x8a, 0xfe, 0x19, 0xdd, 0x6e, 0x5d, 0x53, 0x60, 0x71,
	0x83, 0xfe, 0xbd, 0x41, 0xde, 0xe1, 0x0d, 0xea, 0xdd, 0xdf, 0xa0, 0x7b, 0xde, 0xf6, 0xff, 0xdb,
	0x5b, 0xff, 0x49, 0xde, 0x0e, 0x9e, 0xe8, 0x2d, 0x3c, 0xca, 0xdb, 0x4f, 0x6f, 0x56, 0x1e, 0xff,
	0xc7, 0x3f, 0x8f, 0x5e, 0x5c, 0x5d, 0xac, 0xe6, 0xce, 0x29, 0x8c, 0x59, 0x9f, 0x18, 0xf9, 0xbd,
	0xc7, 0xa9, 0xb3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x63, 0xca, 0xc6, 0x20, 0x04, 0x00,
	0x00,
}
