// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: StoreMod.proto

package proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *MovePhaseSnapMod) Validate() error {
	return nil
}
func (this *ADPhaseSnapMod) Validate() error {
	for _, item := range this.HostCard {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("HostCard", err)
			}
		}
	}
	for _, item := range this.DuelCard {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("DuelCard", err)
			}
		}
	}
	for _, item := range this.HostTrigSkl {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("HostTrigSkl", err)
			}
		}
	}
	for _, item := range this.DuelTrigSkl {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("DuelTrigSkl", err)
			}
		}
	}
	return nil
}
