// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	dtpb "ULZGameDuelService/proto"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ANCHOR: message-struct for game-service
// SECTION: message.proto
// -------------------------------------------------------------
type SESkillCalReq struct {
	IncomeCard           []*dtpb.EventCard  `protobuf:"bytes,1,rep,name=income_card,json=incomeCard,proto3" json:"income_card,omitempty"`
	Feat                 []*dtpb.SkillSet   `protobuf:"bytes,2,rep,name=feat,proto3" json:"feat,omitempty"`
	FromCli              string             `protobuf:"bytes,3,opt,name=from_cli,json=fromCli,proto3" json:"from_cli,omitempty"`
	TargType             dtpb.EventCardType `protobuf:"varint,4,opt,name=targ_type,json=targType,proto3,enum=ULZProto.EventCardType" json:"targ_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SESkillCalReq) Reset()         { *m = SESkillCalReq{} }
func (m *SESkillCalReq) String() string { return proto.CompactTextString(m) }
func (*SESkillCalReq) ProtoMessage()    {}
func (*SESkillCalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SESkillCalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SESkillCalReq.Unmarshal(m, b)
}
func (m *SESkillCalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SESkillCalReq.Marshal(b, m, deterministic)
}
func (m *SESkillCalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SESkillCalReq.Merge(m, src)
}
func (m *SESkillCalReq) XXX_Size() int {
	return xxx_messageInfo_SESkillCalReq.Size(m)
}
func (m *SESkillCalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SESkillCalReq.DiscardUnknown(m)
}

var xxx_messageInfo_SESkillCalReq proto.InternalMessageInfo

func (m *SESkillCalReq) GetIncomeCard() []*dtpb.EventCard {
	if m != nil {
		return m.IncomeCard
	}
	return nil
}

func (m *SESkillCalReq) GetFeat() []*dtpb.SkillSet {
	if m != nil {
		return m.Feat
	}
	return nil
}

func (m *SESkillCalReq) GetFromCli() string {
	if m != nil {
		return m.FromCli
	}
	return ""
}

func (m *SESkillCalReq) GetTargType() dtpb.EventCardType {
	if m != nil {
		return m.TargType
	}
	return dtpb.EventCardType_NULL
}

type SESkillCalResp struct {
	ResultVal            int32                `protobuf:"varint,1,opt,name=result_val,json=resultVal,proto3" json:"result_val,omitempty"`
	EffectResult         []*dtpb.EffectResult `protobuf:"bytes,2,rep,name=effect_result,json=effectResult,proto3" json:"effect_result,omitempty"`
	TargType             dtpb.EventCardType   `protobuf:"varint,3,opt,name=targ_type,json=targType,proto3,enum=ULZProto.EventCardType" json:"targ_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SESkillCalResp) Reset()         { *m = SESkillCalResp{} }
func (m *SESkillCalResp) String() string { return proto.CompactTextString(m) }
func (*SESkillCalResp) ProtoMessage()    {}
func (*SESkillCalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *SESkillCalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SESkillCalResp.Unmarshal(m, b)
}
func (m *SESkillCalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SESkillCalResp.Marshal(b, m, deterministic)
}
func (m *SESkillCalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SESkillCalResp.Merge(m, src)
}
func (m *SESkillCalResp) XXX_Size() int {
	return xxx_messageInfo_SESkillCalResp.Size(m)
}
func (m *SESkillCalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SESkillCalResp.DiscardUnknown(m)
}

var xxx_messageInfo_SESkillCalResp proto.InternalMessageInfo

func (m *SESkillCalResp) GetResultVal() int32 {
	if m != nil {
		return m.ResultVal
	}
	return 0
}

func (m *SESkillCalResp) GetEffectResult() []*dtpb.EffectResult {
	if m != nil {
		return m.EffectResult
	}
	return nil
}

func (m *SESkillCalResp) GetTargType() dtpb.EventCardType {
	if m != nil {
		return m.TargType
	}
	return dtpb.EventCardType_NULL
}

type SEDiceCalReq struct {
	IncomeDice           int32    `protobuf:"varint,1,opt,name=income_dice,json=incomeDice,proto3" json:"income_dice,omitempty"`
	Act                  int32    `protobuf:"varint,2,opt,name=act,proto3" json:"act,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SEDiceCalReq) Reset()         { *m = SEDiceCalReq{} }
func (m *SEDiceCalReq) String() string { return proto.CompactTextString(m) }
func (*SEDiceCalReq) ProtoMessage()    {}
func (*SEDiceCalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *SEDiceCalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SEDiceCalReq.Unmarshal(m, b)
}
func (m *SEDiceCalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SEDiceCalReq.Marshal(b, m, deterministic)
}
func (m *SEDiceCalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SEDiceCalReq.Merge(m, src)
}
func (m *SEDiceCalReq) XXX_Size() int {
	return xxx_messageInfo_SEDiceCalReq.Size(m)
}
func (m *SEDiceCalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SEDiceCalReq.DiscardUnknown(m)
}

var xxx_messageInfo_SEDiceCalReq proto.InternalMessageInfo

func (m *SEDiceCalReq) GetIncomeDice() int32 {
	if m != nil {
		return m.IncomeDice
	}
	return 0
}

func (m *SEDiceCalReq) GetAct() int32 {
	if m != nil {
		return m.Act
	}
	return 0
}

type SEDiceCalResp struct {
	DiceResult           []*DiceResultSet `protobuf:"bytes,1,rep,name=dice_result,json=diceResult,proto3" json:"dice_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SEDiceCalResp) Reset()         { *m = SEDiceCalResp{} }
func (m *SEDiceCalResp) String() string { return proto.CompactTextString(m) }
func (*SEDiceCalResp) ProtoMessage()    {}
func (*SEDiceCalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *SEDiceCalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SEDiceCalResp.Unmarshal(m, b)
}
func (m *SEDiceCalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SEDiceCalResp.Marshal(b, m, deterministic)
}
func (m *SEDiceCalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SEDiceCalResp.Merge(m, src)
}
func (m *SEDiceCalResp) XXX_Size() int {
	return xxx_messageInfo_SEDiceCalResp.Size(m)
}
func (m *SEDiceCalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SEDiceCalResp.DiscardUnknown(m)
}

var xxx_messageInfo_SEDiceCalResp proto.InternalMessageInfo

func (m *SEDiceCalResp) GetDiceResult() []*DiceResultSet {
	if m != nil {
		return m.DiceResult
	}
	return nil
}

type DiceResultSet struct {
	Value                []int32  `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiceResultSet) Reset()         { *m = DiceResultSet{} }
func (m *DiceResultSet) String() string { return proto.CompactTextString(m) }
func (*DiceResultSet) ProtoMessage()    {}
func (*DiceResultSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *DiceResultSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiceResultSet.Unmarshal(m, b)
}
func (m *DiceResultSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiceResultSet.Marshal(b, m, deterministic)
}
func (m *DiceResultSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiceResultSet.Merge(m, src)
}
func (m *DiceResultSet) XXX_Size() int {
	return xxx_messageInfo_DiceResultSet.Size(m)
}
func (m *DiceResultSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DiceResultSet.DiscardUnknown(m)
}

var xxx_messageInfo_DiceResultSet proto.InternalMessageInfo

func (m *DiceResultSet) GetValue() []int32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type SEEffectCalReq struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromTime             *dtpb.EffectTiming `protobuf:"bytes,2,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime               *dtpb.EffectTiming `protobuf:"bytes,3,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	GamesetInstant       *dtpb.GameDataSet  `protobuf:"bytes,4,opt,name=gameset_instant,json=gamesetInstant,proto3" json:"gameset_instant,omitempty"`
	FromCli              string             `protobuf:"bytes,5,opt,name=from_cli,json=fromCli,proto3" json:"from_cli,omitempty"`
	Remark               string             `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SEEffectCalReq) Reset()         { *m = SEEffectCalReq{} }
func (m *SEEffectCalReq) String() string { return proto.CompactTextString(m) }
func (*SEEffectCalReq) ProtoMessage()    {}
func (*SEEffectCalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *SEEffectCalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SEEffectCalReq.Unmarshal(m, b)
}
func (m *SEEffectCalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SEEffectCalReq.Marshal(b, m, deterministic)
}
func (m *SEEffectCalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SEEffectCalReq.Merge(m, src)
}
func (m *SEEffectCalReq) XXX_Size() int {
	return xxx_messageInfo_SEEffectCalReq.Size(m)
}
func (m *SEEffectCalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SEEffectCalReq.DiscardUnknown(m)
}

var xxx_messageInfo_SEEffectCalReq proto.InternalMessageInfo

func (m *SEEffectCalReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SEEffectCalReq) GetFromTime() *dtpb.EffectTiming {
	if m != nil {
		return m.FromTime
	}
	return nil
}

func (m *SEEffectCalReq) GetToTime() *dtpb.EffectTiming {
	if m != nil {
		return m.ToTime
	}
	return nil
}

func (m *SEEffectCalReq) GetGamesetInstant() *dtpb.GameDataSet {
	if m != nil {
		return m.GamesetInstant
	}
	return nil
}

func (m *SEEffectCalReq) GetFromCli() string {
	if m != nil {
		return m.FromCli
	}
	return ""
}

func (m *SEEffectCalReq) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type SEEffectCalResp struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromCli              string             `protobuf:"bytes,2,opt,name=from_cli,json=fromCli,proto3" json:"from_cli,omitempty"`
	GamesetResult        *dtpb.GameDataSet  `protobuf:"bytes,3,opt,name=gameset_result,json=gamesetResult,proto3" json:"gameset_result,omitempty"`
	ResultInfo           []string           `protobuf:"bytes,4,rep,name=result_info,json=resultInfo,proto3" json:"result_info,omitempty"`
	FromTime             *dtpb.EffectResult `protobuf:"bytes,5,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime               *dtpb.EffectResult `protobuf:"bytes,6,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SEEffectCalResp) Reset()         { *m = SEEffectCalResp{} }
func (m *SEEffectCalResp) String() string { return proto.CompactTextString(m) }
func (*SEEffectCalResp) ProtoMessage()    {}
func (*SEEffectCalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *SEEffectCalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SEEffectCalResp.Unmarshal(m, b)
}
func (m *SEEffectCalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SEEffectCalResp.Marshal(b, m, deterministic)
}
func (m *SEEffectCalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SEEffectCalResp.Merge(m, src)
}
func (m *SEEffectCalResp) XXX_Size() int {
	return xxx_messageInfo_SEEffectCalResp.Size(m)
}
func (m *SEEffectCalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SEEffectCalResp.DiscardUnknown(m)
}

var xxx_messageInfo_SEEffectCalResp proto.InternalMessageInfo

func (m *SEEffectCalResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SEEffectCalResp) GetFromCli() string {
	if m != nil {
		return m.FromCli
	}
	return ""
}

func (m *SEEffectCalResp) GetGamesetResult() *dtpb.GameDataSet {
	if m != nil {
		return m.GamesetResult
	}
	return nil
}

func (m *SEEffectCalResp) GetResultInfo() []string {
	if m != nil {
		return m.ResultInfo
	}
	return nil
}

func (m *SEEffectCalResp) GetFromTime() *dtpb.EffectResult {
	if m != nil {
		return m.FromTime
	}
	return nil
}

func (m *SEEffectCalResp) GetToTime() *dtpb.EffectResult {
	if m != nil {
		return m.ToTime
	}
	return nil
}

func init() {
	proto.RegisterType((*SESkillCalReq)(nil), "ULZProto.SESkillCalReq")
	proto.RegisterType((*SESkillCalResp)(nil), "ULZProto.SESkillCalResp")
	proto.RegisterType((*SEDiceCalReq)(nil), "ULZProto.SEDiceCalReq")
	proto.RegisterType((*SEDiceCalResp)(nil), "ULZProto.SEDiceCalResp")
	proto.RegisterType((*DiceResultSet)(nil), "ULZProto.DiceResultSet")
	proto.RegisterType((*SEEffectCalReq)(nil), "ULZProto.SEEffectCalReq")
	proto.RegisterType((*SEEffectCalResp)(nil), "ULZProto.SEEffectCalResp")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0x38, 0x8d, 0x27, 0x4d, 0x0a, 0x0b, 0x14, 0x03, 0x42, 0x8d, 0x2c, 0x81, 0x72,
	0x0a, 0x52, 0xda, 0x03, 0x12, 0x08, 0xa9, 0xa4, 0x11, 0x8a, 0x54, 0x24, 0xb4, 0x49, 0x39, 0xe4,
	0x62, 0x2d, 0xf6, 0x38, 0x5a, 0xd5, 0x5f, 0xd8, 0xdb, 0x48, 0x3d, 0xf2, 0x57, 0x38, 0xf2, 0x23,
	0xf8, 0x5f, 0xdc, 0xd0, 0x7e, 0x24, 0x8d, 0x45, 0x55, 0x95, 0xdb, 0xcc, 0xce, 0x9b, 0xf1, 0x9b,
	0x37, 0x4f, 0x86, 0x5e, 0x86, 0x75, 0xcd, 0x56, 0x38, 0x2a, 0xab, 0x42, 0x14, 0xa4, 0x73, 0x71,
	0xbe, 0xfc, 0x22, 0xa3, 0xe7, 0x70, 0xc6, 0x04, 0xd3, 0xaf, 0xc1, 0x6f, 0x0b, 0x7a, 0xf3, 0xe9,
	0xfc, 0x92, 0xa7, 0xe9, 0x84, 0xa5, 0x14, 0xbf, 0x93, 0x13, 0xe8, 0xf2, 0x3c, 0x2a, 0x32, 0x0c,
	0x23, 0x56, 0xc5, 0xbe, 0x35, 0x70, 0x86, 0xdd, 0xf1, 0xa3, 0xd1, 0xa6, 0x7b, 0x34, 0x5d, 0x63,
	0x2e, 0x26, 0xac, 0x8a, 0x29, 0x68, 0x9c, 0x8c, 0xc9, 0x6b, 0x68, 0x25, 0xc8, 0x84, 0x6f, 0x2b,
	0x38, 0xb9, 0x81, 0xab, 0xd1, 0x73, 0x14, 0x54, 0xd5, 0xc9, 0x33, 0xe8, 0x24, 0x55, 0x91, 0x85,
	0x51, 0xca, 0x7d, 0x67, 0x60, 0x0d, 0x3d, 0xba, 0x27, 0xf3, 0x49, 0xca, 0xc9, 0x09, 0x78, 0x82,
	0x55, 0xab, 0x50, 0x5c, 0x97, 0xe8, 0xb7, 0x06, 0xd6, 0xb0, 0x3f, 0x7e, 0x7a, 0xcb, 0x67, 0x17,
	0xd7, 0x25, 0xd2, 0x8e, 0x44, 0xca, 0x28, 0xf8, 0x69, 0x41, 0x7f, 0x77, 0x81, 0xba, 0x24, 0x2f,
	0x01, 0x2a, 0xac, 0xaf, 0x52, 0x11, 0xae, 0x59, 0xea, 0x5b, 0x03, 0x6b, 0xe8, 0x52, 0x4f, 0xbf,
	0x7c, 0x65, 0x29, 0x79, 0x07, 0x3d, 0x4c, 0x12, 0x8c, 0x44, 0xa8, 0xdf, 0x0c, 0xe7, 0xc3, 0x9d,
	0x6f, 0xa9, 0x32, 0x55, 0x55, 0xba, 0x8f, 0x3b, 0x59, 0x93, 0xa4, 0x73, 0x5f, 0x92, 0xa7, 0xb0,
	0x3f, 0x9f, 0x9e, 0xf1, 0x08, 0x8d, 0xc6, 0x47, 0x5b, 0x8d, 0x63, 0x1e, 0xa1, 0xa1, 0x68, 0xe4,
	0x94, 0x30, 0xf2, 0x00, 0x1c, 0x16, 0x49, 0x66, 0xb2, 0x20, 0xc3, 0x60, 0x26, 0xef, 0xb4, 0x1d,
	0x51, 0x97, 0xe4, 0x2d, 0x74, 0x65, 0xf3, 0x66, 0x09, 0x7d, 0xa7, 0x1d, 0x2e, 0x12, 0xab, 0x49,
	0x4b, 0xf5, 0x21, 0xde, 0xa6, 0xc1, 0x2b, 0xe8, 0x35, 0x8a, 0xe4, 0x31, 0xb8, 0x6b, 0x96, 0x5e,
	0xa1, 0x1a, 0xe2, 0x52, 0x9d, 0x04, 0x7f, 0x94, 0xb2, 0x5a, 0x0b, 0xc3, 0xbb, 0x0f, 0x36, 0x8f,
	0x15, 0x5d, 0x8f, 0xda, 0x3c, 0x26, 0xc7, 0xe0, 0xa9, 0x6b, 0x0a, 0x9e, 0xa1, 0x22, 0x7b, 0x8b,
	0x8c, 0x0b, 0x9e, 0xf1, 0x7c, 0x45, 0xd5, 0xd9, 0x17, 0x3c, 0x43, 0xf2, 0x06, 0xf6, 0x44, 0xa1,
	0x5b, 0x9c, 0x3b, 0x5b, 0xda, 0xa2, 0x50, 0x0d, 0x1f, 0xe0, 0x60, 0xc5, 0x32, 0xac, 0x51, 0x84,
	0x3c, 0xaf, 0x05, 0xcb, 0x85, 0xb2, 0x47, 0x77, 0xfc, 0xe4, 0xa6, 0xf1, 0x13, 0xcb, 0x50, 0xda,
	0x5a, 0xee, 0xda, 0x37, 0xe8, 0x99, 0x06, 0x37, 0x3c, 0xe7, 0x36, 0x3d, 0x77, 0x08, 0xed, 0x0a,
	0x33, 0x56, 0x5d, 0xfa, 0x6d, 0x55, 0x30, 0x59, 0xf0, 0xc3, 0x86, 0x83, 0xc6, 0xee, 0x75, 0xf9,
	0xcf, 0xf2, 0xbb, 0x63, 0xed, 0xe6, 0xd8, 0xf7, 0xb0, 0xe1, 0xb0, 0x39, 0x8f, 0x73, 0x17, 0xe1,
	0x9e, 0x01, 0x1b, 0x8f, 0x1d, 0x41, 0xd7, 0xf8, 0x97, 0xe7, 0x49, 0xe1, 0xb7, 0x06, 0xce, 0xd0,
	0xa3, 0xc6, 0xd2, 0xb3, 0x3c, 0x29, 0x9a, 0xb2, 0xbb, 0xff, 0x2f, 0x7b, 0xfb, 0x3e, 0xb2, 0x7f,
	0x7c, 0xb1, 0x74, 0xd5, 0x3f, 0xe2, 0x97, 0xfd, 0xf0, 0xe2, 0x7c, 0x79, 0x5a, 0xd7, 0x28, 0x46,
	0x0a, 0xfe, 0xb9, 0x88, 0xbf, 0xb5, 0x55, 0xe9, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3,
	0x43, 0xcc, 0xcb, 0x65, 0x04, 0x00, 0x00,
}
